---
# tasks file for k8sworker
#
#
#

          - name: var in node block
            debug:
                    msg: "{{ hostvars['k8s_token']['token'] }}"


          - name: installing docker, iproute-tc
            yum:
                    name:
                            - docker
                            - iproute-tc
                    state: present
            become: true



          - name: enabling docker
            command: systemctl enable docker --now
            become: true



          - name: adding kubernetes repo file
            yum_repository:
                    name: kubernetes
                    description: kubernetes
                    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                    enabled: 1
                    gpgcheck: 1
                    repo_gpgcheck: 1
                    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg  https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                    exclude: kubelet kubeadm kubectl
            become: true



          - name: downloading kubeadm, kubelet, kubectl
            command: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
            become: true


          - name: enabling kubelet
            command: systemctl enable kubelet --now
            become: true


          - name: copying file for setting cgroup drivers as systemd
            copy:
                    src: /home/ec2-user/daemon.json
                    dest: /etc/docker/daemon.json
            become: true



          - name: enabling docker
            service:
                   name: docker
                   state: restarted
            become: true



          - name: creating k8s.conf file
            copy:
                    src: /home/ec2-user/conf
                    dest: /etc/sysctl.d/k8s.conf
            become: true


          - name: running systl command
            command: sysctl --system
            become: true

          - name: joining the master with token command
            shell: "{{ hostvars['k8s_token']['token'] }}"
            become: true



